export const GET_BOOK_BY_ID = 'GET_BOOK_BY_ID';
export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const BOOKS_FETCH_FAILED = 'BOOKS_FETCH_FAILED';
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const BOOK_DETAIL_REQUESTED = 'BOOK_DETAIL_REQUESTED';
